### PR TITLE
add a schema that coerces values

### PR DESCRIPTION
**Pull request by gregwebs**
What do you think? I am trying to stay away from validation right now other than just throwing an exception. My use case is to coerce data from an API into the correct type (and value potentially).

### CODE REVIEW

**Comment by natefaubion** [comment]
I was wanting to put in the ability to do type checking. Originally I was just going to do a map of field names to types, but I like your idea of arbitrary validation/conversion functions better. Type checking could easily be implemented with that and so much more.

I don't know if I want to start putting in a bunch of defaults though besides `all` and some sort of general type checking one as everyone will have slightly different needs.

The problem I had is that the current way of declaring types doesn't let you use other types declared in the same family.

``` js
var List = adt.data({
  Empty: adt.single(),
  Cons: adt.record({
    head: adt.any(),
    tail: adt.only(List) // Not possible since List doesn't exist yet
  })
});
```

It would have to be something far more Scala-like:

``` js
var List = adt.data();
var Empty = adt.single().extends(List);
var Cons = adt.record({
  head: adt.any(),
  tail: adt.only(List)
}).extends(List);
```

The problem with that being that it can't automatically generate the `className` required to work with matches.js. You would have to manually provide it as a parameter, which sucks but may be necessary.

I would really like to work that out before adding this feature and would love some input.

**Comment by gregwebs** [comment]
hmm, is this possible:

``` js
var List = adt.data(function(list){
    list.Empty = adt.single(),
    list.Cons = adt.record({
      head: adt.any(),
      tail: adt.only(list)
    })
});
```

**Comment by gregwebs** [comment]
or possibly something more like:

``` js
var List = adt.data(function(list){ return {
    Empty: adt.single(),
    Cons: list.record({
      head: adt.any(),
      tail: adt.only(list)
    })
  }
});

```

**Comment by gregwebs** [comment]
one more idea:

``` js
tail: function(){ return adt.only(List) }
```

**Comment by gregwebs** [comment]
a decent compomise?

``` js
var List = adt.data()
List.define({
  Empty : adt.single()
  Cons: {
    head: adt.any(),
    tail: adt.only(List)
  }
});
```

**Comment by natefaubion** [comment]
What about something like this?

``` js
var List = adt.data(function (list) {
  // `list` is a reference to `List` with a temporary method called `type` that
  // lets you define members of the family. Once this function returns, `type`
  // will be no longer available to the outside world. `this` is the same `list`.

  // Add a new single class
  this.type('Empty', adt.single());

  // As sugar, you could leave out the second parameter
  this.type('Empty');

  // Add a new record
  this.type('Cons', adt.record(function (cons) {
    // Like with adt.data, `cons` refers to `Cons` with a temp method `field`.
    // `this` is the same as `cons`.
    this.field('head', adt.all());
    this.field('tail', adt.only(list));

    // You can also pass multiple classes to only
    this.field('tail', adt.only(list.Empty, cons))
  }));

  // As sugar, record can take an object literal
  this.type('Cons', adt.record({
    head : adt.all(),
    tail : adt.only(list)
  }));

  // It can also take strings like before. These fields will default to
  // adt.all() to allow any type.
  this.type('Cons', adt.record('head', 'tail'));
});

// As sugar, a data type can just be defined with an object literal. You just
// won't be able to refer to the parent or sibling types.
var List = adt.data({
  Empty : adt.single(),
  Cons  : adt.record('head', 'tail')
});

// We can also add an 'enum' type. All the types defined here will get
// comparison methods (lt, gt, lte, gte). Unfortunately `enum` is reserved.
var Day = adt.enumeration(function (day) {
  this.type('Monday');
  this.type('Tuesday');
  // etc...
});

// As sugar, enums can be defined with just string names.
var Day = adt.enumeration('Monday', 'Tuesday', ...);
```

Or in coffeescript:

``` coffee
List = adt.data (list) ->
  @type 'Empty'
  @type 'Cons'
    head : adt.all()
    tail : adt.only(list)

  # Or
  @type 'Cons', (cons) ->
    @field 'head', adt.all()
    @field 'tail', adt.only('list')
```

This keeps it backwards compatible, while letting you refer to the parent, and also any sibling types (including self). You can define record fields in a specific order if the object literal syntax makes you nervous (though browsers maintain insertion order when iterating). You could also configure prototypes and stuff in the safety of a closure.

**Comment by gregwebs** [comment]
luckily I use coffeescript :)

I like it, could be improved even more with a types function that preserves JSON

``` coffee
List = adt.data (list) ->
  @types 
    Empty: null
    Cons:
      head : adt.all()
      tail : adt.only(list)
```

Or actually, no types function, that is just implied by returning JSON

``` coffee
List = adt.data (list) ->
    Empty: null
    Cons:
      head : adt.all()
      tail : adt.only(list)
```

**Comment by natefaubion** [comment]
Good idea! Hopefully I can work up an implementation tonight to play with.

**Comment by natefaubion** [comment]
Constraint system added in 0.2.1

**Comment by gregwebs** [comment]
looks great!

There were 2 other issues I was addressing on my fork
- use a for loop instead of `.map` which is not available on all older browser versions
- switch to using direct property access rather than `'_' + property` with a getter. What is the point of the getter system? To try to enforce immutability when setting a property?

**Comment by natefaubion** [comment]
1. Yeah, I'll go ahead and switch them over since there's only a few short loops.
2. Yes, to try and enforce immutability. I was toying with the idea of an ecma 5 version that would do away with the explicit function call (mainly for node), but maybe I should just get rid of it all together since its so ugly and noisy?

**Comment by gregwebs** [comment]
for 2) I really like the way you are thinking. However, I think it is fighting the language (unless using ECMA 5 properties). The property can still be changed if someone really wants to. I think it is better to document that `set` should be used for immutable changes unless mutation is desired to optimize performance, and leave it up to the programmer's judgement. For my use case I create the objects once from API data and never modify them: having to append `()` on every get would makes things kind of ugly.

**Comment by natefaubion** [comment]
Added a branch you can test out: https://github.com/natefaubion/adt.js/pull/2

**Pull request closed without merging**
